#!/usr/bin/env python3
"""
Give Hermes autonomy to self-improve on its own, via its NATIVE cron
(dispatched automatically by the running gateway) — no manual runs.

Creates two scheduled jobs:
  1. hermes-self-improve-auto     every 6h, --no-agent script → runs Tier 1
     (discover free models → health → capability rerank). Deterministic, safe,
     reversible, no LLM. This is the low-risk auto-apply you approved.
  2. hermes-self-improve-propose  daily at 03:00 (idle hours), an AGENT job that
     web-researches proven patterns and writes ~/.hermes/PROPOSALS.md for review.
     Proposes only — never edits source/config-core.

Idempotent: re-running replaces the jobs. Use --remove to uninstall.
Requires the gateway to be running (cron only fires then) — check `hermes cron status`.

Usage:
    python3 scripts/setup_autonomy.py            # install/refresh the jobs
    python3 scripts/setup_autonomy.py --remove   # remove them
    python3 scripts/setup_autonomy.py --auto-every 4h --propose-cron "0 2 * * *"
"""
from __future__ import annotations

import os
import re
import shutil
import subprocess
import sys
# Windows-safe console: cp1252 terminals can't encode glyphs like the medical
# staff / check marks; force UTF-8 so prints never crash on Windows.
try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
HERMES_HOME = Path(os.environ.get("HERMES_HOME", Path.home() / ".hermes"))
SCRIPTS_DIR = HERMES_HOME / "scripts"
LAUNCHER = SCRIPTS_DIR / "hermes_self_improve.py"
AUTO_NAME = "hermes-self-improve-auto"
PROPOSE_NAME = "hermes-self-improve-propose"
G, Y, C, DIM, RST = "\033[32m", "\033[33m", "\033[36m", "\033[2m", "\033[0m"

PROPOSE_PROMPT = (
    "Self-improvement research pass for the Hermes system you run on. "
    "Read ~/.hermes/config.yaml and ~/.hermes/self_improve_log.md for current state. "
    "Pick 3-6 concrete improvements across: (a) model chain & routing, (b) prompts & "
    "reasoning-effort/MoA usage, (c) response quality via eval+verify+lesson-cards, "
    "(d) new skills. For each, web-research how comparable open agent projects/papers "
    "solve it and PREFER adapting a proven pattern (cite the source) over inventing. "
    "Give the concrete change (file/command/diff or skill), tag it [AUTO-SAFE] or "
    "[NEEDS-REVIEW], and state how to VERIFY it helped. "
    "Write the result as GitHub-markdown to ~/.hermes/PROPOSALS.md. "
    "IMPORTANT: propose only — do NOT edit Hermes source or config; just write the report."
)


def hermes_bin() -> str:
    return shutil.which("hermes") or "hermes"


def cron(*args) -> subprocess.CompletedProcess:
    return subprocess.run([hermes_bin(), "cron", *args], capture_output=True, text=True)


def jobs_by_name() -> dict[str, str]:
    """Parse `hermes cron list` → {name: job_id}."""
    out = cron("list").stdout
    mapping, cur = {}, None
    for line in out.splitlines():
        m = re.match(r"\s*([0-9a-f]{6,})\s+\[", line)
        if m:
            cur = m.group(1)
            continue
        m = re.match(r"\s*Name:\s+(.+?)\s*$", line)
        if m and cur:
            mapping[m.group(1)] = cur
    return mapping


def remove_named(names) -> None:
    existing = jobs_by_name()
    for n in names:
        if n in existing:
            r = cron("remove", existing[n])
            print(f"  {DIM}removed {n} ({existing[n]}){RST}")


def main() -> int:
    if "--remove" in sys.argv:
        remove_named([AUTO_NAME, PROPOSE_NAME])
        print(f"{G}✓ autonomy jobs removed.{RST}")
        return 0

    auto_every = "6h"
    propose_cron = "0 3 * * *"
    if "--auto-every" in sys.argv:
        auto_every = sys.argv[sys.argv.index("--auto-every") + 1]
    if "--propose-cron" in sys.argv:
        propose_cron = sys.argv[sys.argv.index("--propose-cron") + 1]

    print(f"\n{C}⚕ installing Hermes self-improvement autonomy{RST}\n")

    # 1. launcher under ~/.hermes/scripts/ (cron --script requires it there),
    #    baked with this repo's path so it can find self_improve.py + siblings.
    SCRIPTS_DIR.mkdir(parents=True, exist_ok=True)
    LAUNCHER.write_text(
        "#!/usr/bin/env python3\n"
        "# Auto-generated by hermes-portable setup_autonomy.py — runs Tier-1 self-improve.\n"
        "import subprocess, sys, os\n"
        f"REPO = r'{REPO}'\n"
        "subprocess.run([sys.executable, os.path.join(REPO, 'scripts', 'self_improve.py'), '--auto'],\n"
        "               check=False)\n"
    )
    print(f"  {G}✓{RST} launcher → {LAUNCHER}")

    # 2. (re)create the two cron jobs
    remove_named([AUTO_NAME, PROPOSE_NAME])

    r1 = cron("create", "--no-agent", "--script", LAUNCHER.name,
              f"every {auto_every}", "--name", AUTO_NAME, "--deliver", "local")
    ok1 = r1.returncode == 0
    print(f"  {G if ok1 else Y}{'✓' if ok1 else '✗'}{RST} job '{AUTO_NAME}' — every {auto_every} "
          f"(Tier 1, auto-applied)")
    if not ok1:
        print(f"    {DIM}{(r1.stderr or r1.stdout).strip()[:200]}{RST}")

    r2 = cron("create", propose_cron, PROPOSE_PROMPT,
              "--name", PROPOSE_NAME, "--deliver", "local")
    ok2 = r2.returncode == 0
    print(f"  {G if ok2 else Y}{'✓' if ok2 else '✗'}{RST} job '{PROPOSE_NAME}' — '{propose_cron}' "
          f"(researched proposals → ~/.hermes/PROPOSALS.md)")
    if not ok2:
        print(f"    {DIM}{(r2.stderr or r2.stdout).strip()[:200]}{RST}")

    # 3. gateway must be running for cron to fire
    st = cron("status").stdout
    print()
    if "Gateway is running" in st:
        print(f"{G}✓ gateway is running — jobs will fire automatically.{RST}")
    else:
        print(f"{Y}⚠ gateway not running — cron won't fire until it is.{RST}")
        print(f"  Start it (and keep it running):  hermes gateway start")
        print(f"  Windows: run it at logon via Task Scheduler, or use the OS-idle")
        print(f"  fallback in the README (Task Scheduler 'On idle' → self_improve.py).")
    print(f"\n{DIM}Manage: hermes cron list / pause / resume / remove."
          f"  Uninstall: setup_autonomy.py --remove{RST}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
